server:
  port: 8088
spring:
  # redis 配置
  redis:
    database: 1
    host: 172.26.1.53
    password: 123456
    port: 6379
    timeout: 0
    # redis线程池配置
    jedis:
      pool:
        # 连接池中的最大空闲连接，默认值是8。
        max-idle: 50
        # 连接池中的最小空闲连接，默认值是0。
        min-idle: 10
        # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)。
        max-active: 2000
        # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException
        max-wait: 10000
  # zookeeper地址
  dubbo:
    registry:
      address: 172.26.1.53:2181
    # dubbo协议
    protocol:
      name: dubbo
      # duboo端口号
      port: 20880
  rabbitmq:
    host: 172.26.1.53
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    # 开启发送确认
    publisher-confirms: true
    # 开启发送失败退回
    publisher-returns: true
    # 开启ACK
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
# 日志输出级别
logging:
  level:
    com.cxs: debug